package com.spawpaw.ssm.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.code
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.bedprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Float bedprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.roomprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Float roomprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.description
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.code
     *
     * @return the value of category.code
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.code
     *
     * @param code the value for category.code
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.bedprice
     *
     * @return the value of category.bedprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Float getBedprice() {
        return bedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.bedprice
     *
     * @param bedprice the value for category.bedprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setBedprice(Float bedprice) {
        this.bedprice = bedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.roomprice
     *
     * @return the value of category.roomprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Float getRoomprice() {
        return roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.roomprice
     *
     * @param roomprice the value for category.roomprice
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setRoomprice(Float roomprice) {
        this.roomprice = roomprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description
     *
     * @return the value of category.description
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description
     *
     * @param description the value for category.description
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}