package com.spawpaw.ssm.entity;

public class Faceinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faceinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faceinfo.ptype
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer ptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faceinfo.pid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faceinfo.faceinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private byte[] faceinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faceinfo.id
     *
     * @return the value of faceinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faceinfo.id
     *
     * @param id the value for faceinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faceinfo.ptype
     *
     * @return the value of faceinfo.ptype
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faceinfo.ptype
     *
     * @param ptype the value for faceinfo.ptype
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setPtype(Integer ptype) {
        this.ptype = ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faceinfo.pid
     *
     * @return the value of faceinfo.pid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faceinfo.pid
     *
     * @param pid the value for faceinfo.pid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faceinfo.faceinfo
     *
     * @return the value of faceinfo.faceinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public byte[] getFaceinfo() {
        return faceinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faceinfo.faceinfo
     *
     * @param faceinfo the value for faceinfo.faceinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setFaceinfo(byte[] faceinfo) {
        this.faceinfo = faceinfo;
    }
}