package com.spawpaw.ssm.entity;

import java.util.Date;

public class Guestinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.name
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.level
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.time
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guestinfo.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.id
     *
     * @return the value of guestinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.id
     *
     * @param id the value for guestinfo.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.name
     *
     * @return the value of guestinfo.name
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.name
     *
     * @param name the value for guestinfo.name
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.fid
     *
     * @return the value of guestinfo.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.fid
     *
     * @param fid the value for guestinfo.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.level
     *
     * @return the value of guestinfo.level
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.level
     *
     * @param level the value for guestinfo.level
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.time
     *
     * @return the value of guestinfo.time
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.time
     *
     * @param time the value for guestinfo.time
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestinfo.mid
     *
     * @return the value of guestinfo.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestinfo.mid
     *
     * @param mid the value for guestinfo.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}