package com.spawpaw.ssm.entity;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.state
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.faceimg
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private String faceimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.id
     *
     * @return the value of history.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.id
     *
     * @param id the value for history.id
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.fid
     *
     * @return the value of history.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.fid
     *
     * @param fid the value for history.fid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.state
     *
     * @return the value of history.state
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.state
     *
     * @param state the value for history.state
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.faceimg
     *
     * @return the value of history.faceimg
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public String getFaceimg() {
        return faceimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.faceimg
     *
     * @param faceimg the value for history.faceimg
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setFaceimg(String faceimg) {
        this.faceimg = faceimg == null ? null : faceimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.mid
     *
     * @return the value of history.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.mid
     *
     * @param mid the value for history.mid
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}