package com.spawpaw.ssm.entity;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.cid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.cid
     *
     * @return the value of room.cid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.cid
     *
     * @param cid the value for room.cid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.no
     *
     * @return the value of room.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.no
     *
     * @param no the value for room.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.status
     *
     * @return the value of room.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.status
     *
     * @param status the value for room.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}