package com.spawpaw.ssm.entity;

import java.util.Date;

public class SubscriptionDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.rid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.sid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.sdate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Date sdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.edate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Date edate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.residetype
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer residetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription_dtl.price
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.id
     *
     * @return the value of subscription_dtl.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.id
     *
     * @param id the value for subscription_dtl.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.rid
     *
     * @return the value of subscription_dtl.rid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.rid
     *
     * @param rid the value for subscription_dtl.rid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.sid
     *
     * @return the value of subscription_dtl.sid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.sid
     *
     * @param sid the value for subscription_dtl.sid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.sdate
     *
     * @return the value of subscription_dtl.sdate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.sdate
     *
     * @param sdate the value for subscription_dtl.sdate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.edate
     *
     * @return the value of subscription_dtl.edate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.edate
     *
     * @param edate the value for subscription_dtl.edate
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.residetype
     *
     * @return the value of subscription_dtl.residetype
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getResidetype() {
        return residetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.residetype
     *
     * @param residetype the value for subscription_dtl.residetype
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setResidetype(Integer residetype) {
        this.residetype = residetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription_dtl.price
     *
     * @return the value of subscription_dtl.price
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription_dtl.price
     *
     * @param price the value for subscription_dtl.price
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}