package com.spawpaw.ssm.entity;

import java.util.Date;

public class Subscription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.mid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.linkman
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.email
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.phone
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.cretime
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private Date cretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.remark
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.id
     *
     * @return the value of subscription.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.id
     *
     * @param id the value for subscription.id
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.mid
     *
     * @return the value of subscription.mid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.mid
     *
     * @param mid the value for subscription.mid
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.no
     *
     * @return the value of subscription.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.no
     *
     * @param no the value for subscription.no
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.linkman
     *
     * @return the value of subscription.linkman
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.linkman
     *
     * @param linkman the value for subscription.linkman
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.email
     *
     * @return the value of subscription.email
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.email
     *
     * @param email the value for subscription.email
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.phone
     *
     * @return the value of subscription.phone
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.phone
     *
     * @param phone the value for subscription.phone
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.status
     *
     * @return the value of subscription.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.status
     *
     * @param status the value for subscription.status
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.cretime
     *
     * @return the value of subscription.cretime
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public Date getCretime() {
        return cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.cretime
     *
     * @param cretime the value for subscription.cretime
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setCretime(Date cretime) {
        this.cretime = cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.remark
     *
     * @return the value of subscription.remark
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.remark
     *
     * @param remark the value for subscription.remark
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}