package com.spawpaw.ssm.dao;

import com.spawpaw.ssm.entity.Guestinfo;
import com.spawpaw.ssm.entity.GuestinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuestinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int countByExample(GuestinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int deleteByExample(GuestinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int insert(Guestinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int insertSelective(Guestinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    List<Guestinfo> selectByExample(GuestinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    Guestinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") Guestinfo record, @Param("example") GuestinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByExample(@Param("record") Guestinfo record, @Param("example") GuestinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByPrimaryKeySelective(Guestinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guestinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByPrimaryKey(Guestinfo record);
}