package com.spawpaw.ssm.dao;

import com.spawpaw.ssm.entity.Monitorinfo;
import com.spawpaw.ssm.entity.MonitorinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MonitorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int countByExample(MonitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int deleteByExample(MonitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int insert(Monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int insertSelective(Monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    List<Monitorinfo> selectByExample(MonitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    Monitorinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") Monitorinfo record, @Param("example") MonitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByExample(@Param("record") Monitorinfo record, @Param("example") MonitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByPrimaryKeySelective(Monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitorinfo
     *
     * @mbggenerated Mon Feb 19 12:24:04 CST 2018
     */
    int updateByPrimaryKey(Monitorinfo record);
}