package com.spawpaw.ssm.dao;

import com.spawpaw.ssm.entity.Reside;
import com.spawpaw.ssm.entity.ResideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int countByExample(ResideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int deleteByExample(ResideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int insert(Reside record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int insertSelective(Reside record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    List<Reside> selectByExample(ResideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    Reside selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Reside record, @Param("example") ResideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByExample(@Param("record") Reside record, @Param("example") ResideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByPrimaryKeySelective(Reside record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reside
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByPrimaryKey(Reside record);
}