package com.spawpaw.ssm.dao;

import com.spawpaw.ssm.entity.Subscription;
import com.spawpaw.ssm.entity.SubscriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubscriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int countByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int deleteByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int insert(Subscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int insertSelective(Subscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    List<Subscription> selectByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    Subscription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") Subscription record, @Param("example") SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByExample(@Param("record") Subscription record, @Param("example") SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByPrimaryKeySelective(Subscription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription
     *
     * @mbggenerated Thu Jan 04 16:26:19 CST 2018
     */
    int updateByPrimaryKey(Subscription record);
}